**Numpy es un modulo cuyos objetos pueden ser utilizados para representar matrices y vectores, y con ellos hacer las operaciones entre matrices y vectores que conocemos.**

**Comenzamos importando este modulo como np.**

In [1]:
import numpy as np

**Si v es un vector de longitud n, entonces en numpy se puede representar como,**

**v = np.array([ v0 , v1 , v2 , v3 ,..., vn-2 , vn-1 ]).**





**Si A es una matriz de nxn, entonces en numpy se puede representar como,**

**A = np.array([ [A00,A01,...,A0n-1] , [A10,A11,...,A1n-1] , [A20,A21,...,A2n-1] ,..., [An-10,An-11,...,An-1n-1] ]).**

**Es decir, el primer corchete de A representa a la primera fila de A, el segundo corchete de A representa a la segunda fila de A, ....**

**Supongamos que v  es de longitud 3 y A es de 3x3**

In [2]:
v = np.array([3,4,1])

A = np.array([[4,5,1],[1,8,2],[8,10,2]])

print('v =',v)
print('')
print('A =')
print(A)

v = [3 4 1]

A =
[[ 4  5  1]
 [ 1  8  2]
 [ 8 10  2]]


**Con shape podemos ver la forma que tienen v y A**

In [3]:
print('La forma de v es,',v.shape)
print('')
print('La forma de A es,',A.shape)


B = np.array([[4,5,1],[1,8,2]])

print('')
print('La forma de B es,',B.shape)

C = np.array([[4,5],[1,2],[10,2]])
print('')
print('La forma de C es,',C.shape)

La forma de v es, (3,)

La forma de A es, (3, 3)

La forma de B es, (2, 3)

La forma de C es, (3, 2)


## **Antes de seguir hay que hacer una aclaracion muy importante**

## **En python, y por lo tanto en numpy, los indices de un vector o una matriz comienzan a contarse desde el cero.**

**Luego, el primer elemento del vector v seria v_primero = v[0]**

**El segundo elemento del vector v seria v_segundo = v[1]**

.

.

**Etc** 

**Observar que si v es de longitud n, entonces el numero que esta adentro del corchete (v[numero]) va desde 0 hasta n-1.**


**Si quiero obtener el tercer elemento de la segunda fila de A:**

**A_tercer_elemento_de_la_segunda_fila = A[1,2]**

**A[j,k] j representa la fila y k representa a la columna.** 

**Si quiero obtener la tercera fila de A:**

**A_tercera_fila = A[2,:]**

**Si quiero obtener la cuarta columna de A:**

**A_cuarta_columna = A[:,3]**


In [4]:
v = np.array([3,4,1])

v_segundo = v[1]

print('El segundo elemento de v es',v_segundo )


A = np.array([[4.6,5,1],[1.4,8,7.2],[8.2,10,2]])

A_tercer_elemento_de_la_segunda_fila = A[1,2]

print('El tercer elemento de la segunda fila de A es', A_tercer_elemento_de_la_segunda_fila)


A_tercera_fila = A[2,:]

print('La tercera fila de A es', A_tercera_fila)

A_primera_columna = A[:,0]

print('La primera columna de A es', A_primera_columna)


El segundo elemento de v es 4
El tercer elemento de la segunda fila de A es 7.2
La tercera fila de A es [ 8.2 10.   2. ]
La primera columna de A es [4.6 1.4 8.2]


**Podemos crear vectores y matrices muy grandes y luego hacer operaciones algebraicas con ellos.**

**Por ejemplo,**
 
**A = numpy.ones((3,2)) es una matriz de 3x2 llena de unos**

**A = numpy.zeros((200,300)) es una matriz de 200x300 llena de ceros.**

In [5]:
v = np.ones(20)

print('v =',v)
print('')

A = np.ones((3,2))

print('A =')
print(A)
print('')

B = np.zeros((30,40))

print('B =')
print(B)

v = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

A =
[[1. 1.]
 [1. 1.]
 [1. 1.]]

B =
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


**Tambien suele usarse v = np.linspace(b,c,N).**


**En este caso v es un vector de N elementos cuyo elemento j es igual a,** 

**v[ j ] = b + (j/(N-1))*(c-b)**


In [6]:
v = np.linspace(-3.6,20.8,10)
print('v = ', v)
print('')

u = np.linspace(0,14,15)
print('u = ', u)

v =  [-3.6        -0.88888889  1.82222222  4.53333333  7.24444444  9.95555556
 12.66666667 15.37777778 18.08888889 20.8       ]

u =  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


**Otro util es v = np.arange(b, c, dt)**

**Que es un vector que va de b a c tomando saltos de tamaño dt.**

In [7]:
v = np.arange(5,18,0.15)
print('v = ', v)
print('')

v =  [ 5.    5.15  5.3   5.45  5.6   5.75  5.9   6.05  6.2   6.35  6.5   6.65
  6.8   6.95  7.1   7.25  7.4   7.55  7.7   7.85  8.    8.15  8.3   8.45
  8.6   8.75  8.9   9.05  9.2   9.35  9.5   9.65  9.8   9.95 10.1  10.25
 10.4  10.55 10.7  10.85 11.   11.15 11.3  11.45 11.6  11.75 11.9  12.05
 12.2  12.35 12.5  12.65 12.8  12.95 13.1  13.25 13.4  13.55 13.7  13.85
 14.   14.15 14.3  14.45 14.6  14.75 14.9  15.05 15.2  15.35 15.5  15.65
 15.8  15.95 16.1  16.25 16.4  16.55 16.7  16.85 17.   17.15 17.3  17.45
 17.6  17.75 17.9 ]



**Con np.reshape() se puede modificar la forma de un vector v o una matriz A.**

In [8]:
u = np.linspace(0,14,15)

print('u =',u)
print('')

uu = u.reshape(3,5)

print('uu =')
print(uu)

print('')
print('La forma de uu es',uu.shape)
print('')

A = np.array([[5,-6,3,5],[5,-1,9,2],[25,-6,1,7],[4,-5,7,8]])

print('A =')
print(A)

print('')
print('La forma de A es',A.shape)

AA = A.reshape(2,8)

print('')

print('AA =')
print(AA)

print('')
print('La forma de AA es',AA.shape)

u = [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]

uu =
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]

La forma de uu es (3, 5)

A =
[[ 5 -6  3  5]
 [ 5 -1  9  2]
 [25 -6  1  7]
 [ 4 -5  7  8]]

La forma de A es (4, 4)

AA =
[[ 5 -6  3  5  5 -1  9  2]
 [25 -6  1  7  4 -5  7  8]]

La forma de AA es (2, 8)


**Cada elemento de una matriz o de un vector puede redefinirse** 

**Por ejemplo:**

In [9]:
A = np.array([[5,-6,5],[5,-1,2],[-6,1,7]])

print('A =')
print(A)
print('')

A[2,1] = 555 

print('A =')
print(A)

A =
[[ 5 -6  5]
 [ 5 -1  2]
 [-6  1  7]]

A =
[[  5  -6   5]
 [  5  -1   2]
 [ -6 555   7]]


**Tambien se puede redefinir alguna columna o fila de nuestra matriz** 

**Por ejemplo:**

In [10]:
A = np.array([[5,-6,5],[5,-1,2],[-6,1,7]])

print('A =')
print(A)
print('')

A[1,:] = np.array([-200,-300,-400]) 

print('A =')
print(A)
print('')

A[:,2] = np.array([-200,-300,-400]) 

print('A =')
print(A)

A =
[[ 5 -6  5]
 [ 5 -1  2]
 [-6  1  7]]

A =
[[   5   -6    5]
 [-200 -300 -400]
 [  -6    1    7]]

A =
[[   5   -6 -200]
 [-200 -300 -300]
 [  -6    1 -400]]


**Se puede usar el for para redefinir los elementos de una matriz gigante:**

In [11]:
A = np.ones((100,200))

for j in list(range(A.shape[0])):

    for k in list(range(A.shape[1])):

        A[j,k] = pow(j*k,0.5) + np.cos(k)

print('A =')
print(A)

A =
[[  1.           0.54030231  -0.41614684 ...  -0.60555186  -0.99682859
   -0.47162571]
 [  1.           1.54030231   0.99806673 ...  13.43011698  13.07441868
   13.63511027]
 [  1.           1.95451587   1.58385316 ...  19.24388138  18.90292015
   19.47831163]
 ...
 [  1.          10.38916011  13.51224144 ... 137.62975477 137.58888495
  138.463611  ]
 [  1.          10.43979724  13.58385316 ... 138.34048082 138.3014126
  139.17793569]
 [  1.          10.49017668  13.65510044 ... 139.04758988 139.01031408
  139.88862507]]


#**Hasta ahora vimos cosas mas relacionadas con la definicion de matrices y vectores. Algunas mastrices definidas resultaron se gigantes y seria interezante realizar operaciones con ellas.** 

#**Se imaginan calcular el determinante de una matriz de 1000x1000 a mano ?** 

**Hagamos operaciones algebraicas con dos vectores llamados v y u** 

In [12]:
v = np.array([4,5,6])

u = np.array([2,5,3])

**Si queremos multiplicar un vector por un ecalar,**

In [13]:
v_5 = 5*v   # multiplico v por 5

print('v_5 =',v_5)

v_5 = [20 25 30]


**Si queremos sumar dos vectores o hacer una combinacion lineal entre ellos,**

In [14]:
r = v + u 

print('r =',r)
print('')

z = 3*v + (-6)*u 
z = 3*v-6*u

print('z =',z)

r = [ 6 10  9]

z = [  0 -15   0]


**Si queremos hacer el producto interno entre dos vectores v y u, usamos np.dot(v,u),**

In [15]:
v = np.array([4,5,6])

u = np.array([2,5,3])

prod_int = np.dot(v,u) 

print('El producto interno entre v y u es,',prod_int)

prod_int = np.dot(u,v) 

print('El producto interno entre u y v es,',prod_int)

prod_int = np.dot(v,-1*u) 

print('El producto interno entre v y -u es,',prod_int)

El producto interno entre v y u es, 51
El producto interno entre u y v es, 51
El producto interno entre v y -u es, -51


**La norma de un vector v se puede calcular con np.linalg.norm(v)**

In [16]:
v = np.array([4,5,6])

norma_v = np.linalg.norm(v)

print('La norma de v es,',norma_v)
print('')

# normalicemos a v,

v_normalizado = v/norma_v

print('v_normalizado =',v_normalizado)
print('')

# veamos que en efecto v_normalizado es v normalizado

print('El producto interno entre v_normalizado y v_normalizado es,',np.dot(v_normalizado,v_normalizado),'= 1')




La norma de v es, 8.774964387392123

v_normalizado = [0.45584231 0.56980288 0.68376346]

El producto interno entre v_normalizado y v_normalizado es, 0.9999999999999999 = 1


**De la misma manera que se realizo el producto entre vectores, se puede realizar el producto entre dos matrices A y B.**

**Por supuesto, la multiplicacion entre matrices es no conmutativa**

In [17]:
A = np.array([[5,-6,1],[5,-1,9],[-2,4,2]])

print('A =',A)
print('')

B = np.array([[5,0,-3],[3,1,-4],[5,3,-1]])

print('B =',B)
print('')

C_AB = np.dot(A,B)

print('C_AB =',C_AB)


C_BA = np.dot(B,A)

print('C_BA =',C_BA)

A = [[ 5 -6  1]
 [ 5 -1  9]
 [-2  4  2]]

B = [[ 5  0 -3]
 [ 3  1 -4]
 [ 5  3 -1]]

C_AB = [[ 12  -3   8]
 [ 67  26 -20]
 [ 12  10 -12]]
C_BA = [[ 31 -42  -1]
 [ 28 -35   4]
 [ 42 -37  30]]


**Tambien puedo hacer A*v**

In [18]:
A = np.array([[5,-6,1],[5,-1,9],[-2,4,2]])
v = np.array([4,5,6])

Av = np.dot(A,v)

print('Av = ', Av)

Av =  [-4 69 24]


**Si quiero transponer el vector v o la matriz A uso .T.**

**Vemamos la regla de transposicion del producto,  (AB)^T = (B^T)(A^T)**


In [19]:
A = np.array([[5,-6,1,4,6],[5,-1,9,6,1]])

B = np.array([[-1,3,1],[5,6,2],[7,4,8],[-1,9,3],[1,2,4]])

C = np.dot(A,B)

print('AB =')
print(C)

print('')

print('(AB)^T=')
print(C.T)


A_T = A.T

B_T = B.T 

print('')

print('(B^T)(A^T)  =')
print(np.dot(B_T,A_T))

AB =
[[-26  31  37]
 [ 48 101  97]]

(AB)^T=
[[-26  48]
 [ 31 101]
 [ 37  97]]

(B^T)(A^T)  =
[[-26  48]
 [ 31 101]
 [ 37  97]]


**El determinante de una matriz cuadrada A se puede calcular con np.linalg.det(A)**

In [20]:
A = np.array([[2,3],[5,1]])

det_A = np.linalg.det(A)

print('El determinante de A es igual a',det_A)

El determinante de A es igual a -13.0


**Si A no es cuadrada entonces su determinante no puede ser calculado,**

In [21]:
# A no es cuadrada entonces python va a tirar error

A = np.array([[2,3],[5,1],[4,3]])

det_A = np.linalg.det(A)

LinAlgError: Last 2 dimensions of the array must be square

**Si A tiene una fila que es una combinacion lineal de otras filas, entonces el determinante de A es 0. Lo mismo pasa con las columnas.** 

**En algunos casos python da un numero muy pequeño para el Detminante pero no da cero, esto es un error del programa relacionado con que los numeros se almacenan como puntos flotantes.**

In [22]:
# por ejemplo, en este caso, la tercera fila de A es primera_fila-2*segunda_fila

A = np.array([[2,3,6],[4,1,1],[-6,1,4]])

det_A = np.linalg.det(A)

print('El determinante de A es igual a',det_A)

El determinante de A es igual a -8.881784197001224e-15


**Si A tiene determinante distinto de cero, podemos calcular su inverza, np.linalg.inv(A)**

**Podemos ver que si multiplicamos a A por su inverza, python nos da una matriz muy parecida a la identidad. De nuevo, las diferencias con la identidad se deben a problemas relacionados con el punto flotante.**

In [23]:
A = np.array([[2,3],[5,1]])

print('A =')
print(A)
print('')

A_inv = np.linalg.inv(A)

print('A_inv =')
print(A_inv)
print('')

AA_inv = np.dot(A,A_inv)

print('AA_inv=')
print(AA_inv)
print('')

A_invA = np.dot(A_inv,A)

print('A_invA =')
print(A_invA)

A =
[[2 3]
 [5 1]]

A_inv =
[[-0.07692308  0.23076923]
 [ 0.38461538 -0.15384615]]

AA_inv=
[[ 1.00000000e+00 -5.55111512e-17]
 [-5.55111512e-17  1.00000000e+00]]

A_invA =
[[ 1.00000000e+00 -2.77555756e-17]
 [-1.11022302e-16  1.00000000e+00]]


**Una propiedad del determinante es que el det(AB) = det(A)det(B)**

**AA^(-1) = 1,**

**Aplicando el determinante a ambos lados de la igualdad y usando la propiedad del producto de los determinantes,**

**det(A)det(A^(-1)) = det(1) = 1**,

**Luego, det(A^(-1)) = [det(A)]^(-1)**

**Veamos que esta propiedad se cumple.** 

In [24]:
A = np.array([[2,3],[5,1]])

A_inv = np.linalg.inv(A)


det_A = np.linalg.det(A)

det_A_inv = np.linalg.det(A_inv)


print('det_A*det_A_inv =',det_A*det_A_inv)


det_A*det_A_inv = 0.9999999999999996


**Algunas veces puede resultar util definir una matriz B que sea el resultado de eliminar alguna fila o alguna columna de la matriz A, esto se hace con B = np.delete(A, j, k).** 

**B = np.delete(A, j, k)**

**El k puede ser k = 0 o k = 1.** 

**k = 0 implica quitar fila j**

**k = 1 implica quitar columna j**

**Luego,**

**Si k = 0, B seria el resultado de quitarle la fila j a A.** 

**Si k = 1, B seria el resultado de quitarle la columna j a A.** 



**Veamos con dos ejemplos:**

In [26]:
A = np.array([[1,2,3,4], [5,6,8,1], [9,10,12,3],[9,11,12,5]])

B = np.delete(A, 2, 1) # le quito a A la fila 2
print('A =')
print(A)

print(np.delete(A, 2, 1))

A =
[[ 1  2  3  4]
 [ 5  6  8  1]
 [ 9 10 12  3]
 [ 9 11 12  5]]
[[ 1  2  4]
 [ 5  6  1]
 [ 9 10  3]
 [ 9 11  5]]


# **Hagamos un parentesis antes de seguir con los vectores y matrices** 

**En python, en matematica, y en fisica, una funcion es una maquina al que le entran algunos objetos y te devuelve objetos cuyos valores o naturaleza puede depender de los valores y naturaleza de los objetos que ingresaron.**

**En python se puede armar funciones con def**.

**Veamos un ejemplo simple:**

In [ ]:
def combinacion_lienal(a,b,A,B):

    C = a*A+b*b

    return C

**La funcion de arriba tiene como entrada 4 objetos que pueden ser escalares. En el caso en el que fueran escalares, la funcion nos va a devolver un escalar.**

In [ ]:
combinacion_lienal(2,3,7,5)

23

**Pero tambien podemos hacer que algunos objetos de entrada sean matrices**

In [ ]:
A = np.array([[4,5],[1,6]])

B = np.array([[2,1],[7,3]])

combinacion_lienal(2,3,A,B)

array([[17, 19],
       [11, 21]])

**Podemos hacer una funcion tan complicada como queramos que utilice los productos internos entre los objetos de entrada, los determinantes de los objetos de entrada, los cosenos de estos objetos, etc**

**Tambien podemos definir una funcion recurrente. Las funciones recurrentes son aquellas que utilizan a la misma funcion dentro de la funcion**.

**Por ejemplo, se puede armar una funcion recurrente para calcular el factocial de un natural N.**

In [ ]:
def fac(N):

   if N == 0:

      return 1

   else:
       
      return N*fac(N-1)  #observar que aca se vuelve a usar la misma funcion



fac_5 = fac(5)

print('El factorial de 5 es',fac_5)

El factorial de 5 es 120


In [ ]:
fac_20 = fac(20)

Edad_del_universo_en_segundos = (14*(10**9))*(365)*(24)*(60)*(60)   

# El universo tiene 14 mil millones de años, cada año 365 dias, cada dia 24 hs,...

print('Si quiero hacer todos los ordenamientos posibles de 20 libros tardando un segundo para ir de un ordenamiento al otro, entonces voy a tardar'

,fac_20/Edad_del_universo_en_segundos,'veces la edad del unverso')

Si quiero hacer todos los ordenamientos posibles de 20 libros tardando un segundo para ir de un ordenamiento al otro, entonces voy a tardar 5.510486899726027 veces la edad del unverso


# **Cerremos el parentesis y volvamos a los vectores y matrices** 

**En la pagina 33 de la guia teorica, se muestra el metodo para calcular determinantes a partir de los cofactores. Los cofactores son los determinantes de las matrices que se obtienen al eliminar la fila y la columna correspondiente al elemto en el que estamos parados.**

**Podemos utilizar una funcion recurrente para calcular el determinante de una matriz A. La matriz A es el objeto de entrada, en el interior de la funcion calculadora de determinantes que armemos se va a necesitar calcular un cofactor, es decir, el determinante de una matriz. Es en ese punto donde vamos a llamar otra vez a nuestra funcion calculadora de determinantes.** 

In [ ]:
def det(A):

    if A.shape[0]==1:

      return A[0,0]  
      # si A es una matriz formada por un unico elemento, entonces el determinante de A es el valor de ese elemento. 

    else:

         Det = 0   

         # voy a calcular el determinante de A usando los cofactores de la primera fila (llamada fila 0).

         A_sin_fila_0 = np.delete(A, 0, 0) 

         for j in list(range(A.shape[0])):

            A_sin_fila_0_y_sin_colum_j = np.delete(A_sin_fila_0, j, 1)

            # a medida que voy recorriendo los elementos de la fila cero tengo que ir eliminando la columna j en la que estoy parado.

            Det = Det + A[0,j]*pow(-1,j)*det(A_sin_fila_0_y_sin_colum_j)

            # aqui llamos otra vez a la funcion para que me calcule el determinante 
            # de la matriz que so obtiene al eliminar la primera fila y la columna j. 
    
         return Det   

**Veamos con un ejemplo que tan bien funciona nuestra funcion calculadora de determinantes:**

In [ ]:
A = np.array([[2,3,-5,-25],[5,-1,2,11],[-12,0,-2,8],[6,-7,-5,1]])

det_A = np.linalg.det(A)

det_A_nuestra_funcion = det(A)

print('El determinate calculado por numpy es',det_A)

print('El determinate calculado por nuestra funcion es',det_A_nuestra_funcion)


El determinate calculado por numpy es -5383.999999999997
El determinate calculado por nuestra funcion es -5384


In [ ]:
def operaciones(N):

    if N == 2:

       return 3

    else:

       return N*operaciones(N-1) + N + (N-1) 

In [ ]:
print('cantidad de operaciones para 20x20 =',operaciones(20)) 

cantidad de operaciones para 20x20 = 6613313319248079999


In [ ]:
print('cantidad de operaciones para 9x9 =',operaciones(9)) 

cantidad de operaciones para 9x9 = 986408


In [ ]:
import timeit 

%timeit 50 + 561

%timeit 50 * 561

14.2 ns ± 1.53 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
15.6 ns ± 2.97 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [ ]:
print('Tiempo que tardaria la computadora en calcular el determinante =',operaciones(9)*(15)*(10**-9), 's')

Tiempo que tardaria la computadora en calcular el determinante = 0.014796120000000001 s


In [ ]:
A = np.ones((9,9))

for j in range(9):

    for k in range(9):

        A[j,k] = 2*np.random.rand(1)[0]-1

In [ ]:
%timeit det(A)

6.15 s ± 793 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit np.linalg.det(A)

5.8 µs ± 115 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
